#168 alter Expecting enum to be a bitflag
kdr-aus/ogma pull request #169
Opened 2022-09-03 02:08 UTC by yuchunzhou

2022-09-05 23:46 UTC, kurtlawrence requested changes
Thanks @yuchunzhou, I've just got a couple of changes that I would like implemented.

2022-09-05 23:46 UTC, kurtlawrence commented on ogma/src/lang/syntax/parse.rs
> +bitflags! {
Change to `bitflags::bitflags!`

2022-09-05 23:46 UTC, kurtlawrence commented on ogma/src/lang/syntax/parse.rs
> +use bitflags::bitflags;
Removing import, it is only used once, so we can use qualified name for it.

2022-09-05 23:46 UTC, kurtlawrence commented on ogma/src/lang/syntax/parse.rs
> +#![allow(non_upper_case_globals)]
Remove

2022-09-05 23:46 UTC, kurtlawrence commented on ogma/src/lang/syntax/parse.rs
> +	const Impl = 0b00001;
I am happy to capitalise the constants.

2022-09-05 23:46 UTC, kurtlawrence commented on ogma/src/lang/syntax/parse.rs
> +	const None = 0b10000;
Please set `const NONE = 0;`
It will match **all** numbers, but also acts as the empty value.

2022-09-06 03:04 UTC, yuchunzhou commented
hi @kurtlawrence, the code is updated.

2022-09-06 03:38 UTC, kurtlawrence approved these changes

2022-09-06 03:56 UTC, merged

2022-09-06 03:57 UTC, kurtlawrence commented
Thanks @yuchunzhou, I've merged it in, despite the CI failures. I've got a fix anyway coming through.